Repository moxb/moxb, pull requests merged in 2018-10, with the labels that each got.

#26 Improve testing
  Makefile
  admin/node-installation/.npm-version
  admin/node-installation/install.sh
  examples/Makefile
  examples/package-lock.json
  examples/package.json
  jest.config.js
  package-lock.json
  package.json
  packages/antd/package.json
  packages/antd/src/__tests__/ActionAnt.test.tsx
  packages/antd/src/__tests__/ActionUi.test.tsx
  packages/antd/src/__tests__/TextAnt.test.tsx
  packages/antd/src/__tests__/__snapshots__/ActionAnt.test.tsx.snap
  packages/antd/src/__tests__/__snapshots__/TextAnt.test.tsx.snap
  packages/moxb/package-lock.json
  packages/moxb/package.json
  packages/semui/package-lock.json
  packages/semui/package.json
  packages/semui/src/__tests__/ActionUi.test.tsx
Labels: PR - Under Review

#28 build improvements
  ChangeLog.md
  Makefile
  admin/bin/watch-packages.sh
  admin/makefiles/package.mk
  jest.config.js
  packages/antd/package.json
  packages/antd/src/TextAnt.tsx
  packages/meteor/src/MeteorTableFetcher.ts
  packages/moxb/src/form/FormItem.ts
  packages/semui/package.json
  tsconfig.test.json
Labels: PR - Under Review

#29 fix make watch all
  ChangeLog.md
  Makefile
Labels: @moxb, PR - Under Review

#31 Add invalidateData() hook for meteor tables
  packages/meteor/src/MeteorDataFetcher.ts
  packages/meteor/src/MeteorTableImpl.ts
  packages/meteor/src/MeteorTableOperations.ts
  packages/meteor/src/MethodDataFetcherImpl.ts
  packages/meteor/src/index.ts
  packages/moxb/src/table/TableImpl.ts
Labels: @moxb/meteor, PR - Under Review

#32 Debugging and Build improvements
  ChangeLog.md
  Makefile
  admin/makefiles/package.mk
  examples/Makefile
  examples/tsconfig.json
  packages/antd/.gitignore
  packages/antd/package.json
  packages/antd/tsconfig.json
  packages/meteor/.gitignore
  packages/meteor/package.json
  packages/meteor/tsconfig.json
  packages/moxb/.gitignore
  packages/moxb/package.json
  packages/moxb/tsconfig.json
  packages/semui/.gitignore
  packages/semui/package.json
  packages/semui/tsconfig.json
  tsconfig.test.json
Labels: @moxb, PR - Under Review

#34 Bug fix: run `tsc` when makefile etc change
  ChangeLog.md
  admin/makefiles/package.mk
  packages/antd/package.json
  packages/meteor/package.json
  packages/moxb/package-lock.json
  packages/semui/package.json
Labels: @moxb, Bug, PR - Under Review

#35 Fix form submit and errors
  ChangeLog.md
  examples/src/app/ApplicationAnt.tsx
  examples/src/form/LoginFormUi.tsx
  packages/antd/src/ActionAnt.tsx
  packages/antd/src/__tests__/__snapshots__/ActionAnt.test.tsx.snap
  packages/moxb/src/form/Form.ts
  packages/moxb/src/form/FormImpl.ts
  packages/moxb/src/form/__tests__/Form.test.ts
Labels: @moxb, PR - Ready for Review

#38 Add a new component and CI
  .travis.yml
  Makefile
  examples/src/app/ApplicationAnt.tsx
  packages/antd/src/OneOfAnt.tsx
  packages/moxb/src/form/Form.ts
  packages/moxb/src/form/FormImpl.ts
  packages/moxb/src/form/__tests__/Form.test.ts
Labels: PR - Under Review

#36 Some more makefile fixes
  ChangeLog.md
  Makefile
  admin/makefiles/package.mk
  examples/Makefile
Labels: PR - Ready for Review

#42 Tighten up TS config a bit
  examples/Makefile
  examples/package.json
  examples/tsconfig.json
  packages/antd/package.json
  packages/antd/src/BindAnt.tsx
  packages/antd/src/DatePickerAnt.tsx
  packages/antd/src/ModalAnt.tsx
  packages/antd/src/TableAnt.tsx
  packages/antd/src/TimePickerAnt.tsx
  packages/antd/src/__tests__/FormItemAnt.test.tsx
  packages/antd/src/__tests__/TableAnt.test.tsx
  packages/antd/tsconfig.json
  packages/meteor/package.json
  packages/moxb/package.json
  packages/moxb/src/i18n/i18n.ts
  packages/moxb/src/table/TableSortImpl.ts
  packages/moxb/src/table/__tests__/TableImpl.test.ts
  packages/moxb/src/util/idToDomId.ts
  packages/moxb/src/util/toJSON.ts
  packages/moxb/src/value/__tests__/ValueImplTest.test.ts
  packages/moxb/tsconfig.json
  packages/semui/package.json
  packages/semui/src/ManyOfUi.tsx
  packages/semui/src/OneOfUi.tsx
  packages/semui/src/TablePaginationUi.tsx
  packages/semui/tsconfig.json
Labels: @moxb, PR - Under Review

#44 Add TagAnt component
  examples/package.json
  examples/src/app/Application.ts
  examples/src/app/ApplicationAnt.tsx
  examples/src/app/ApplicationImpl.ts
  examples/src/memtable/MemTableAnt.tsx
  packages/antd/src/DatePickerAnt.tsx
  packages/antd/src/TagAnt.tsx
  packages/antd/src/TimePickerAnt.tsx
  packages/antd/src/index.ts
  packages/moxb/src/date/Date.ts
  packages/moxb/src/date/DateImpl.ts
  packages/moxb/src/time/Time.ts
  packages/moxb/src/time/TimeImpl.ts
  packages/moxb/src/value/ValueImpl.ts
Labels: PR - Under Review
