Repository moxb/moxb, pull requests merged in 2018-12, with the labels that each got.

#64 Enhance OneOf
  packages/antd/src/OneOfAnt.tsx
  packages/moxb/src/one-of/OneOf.ts
Labels: PR - Under Review

#65 Add pending state to actions
  packages/antd/src/ActionAnt.tsx
  packages/antd/src/__tests__/__snapshots__/ActionAnt.test.tsx.snap
  packages/moxb/src/action/Action.ts
  packages/moxb/src/action/ActionImpl.ts
Labels: PR - Under Review

#67 CustomData bind
  packages/moxb/src/bind/Bind.ts
  packages/moxb/src/bind/BindImpl.ts
  packages/moxb/src/table/Table.ts
Labels: PR - Under Review

#68 Make it possible to explain why a given action (or bind) is disabled
  packages/antd/src/ActionAnt.tsx
  packages/antd/src/BindAnt.tsx
  packages/antd/src/__tests__/__snapshots__/ActionAnt.test.tsx.snap
  packages/antd/src/__tests__/__snapshots__/BoolAnt.test.tsx.snap
  packages/antd/src/__tests__/__snapshots__/DatePickerAnt.test.tsx.snap
  packages/antd/src/__tests__/__snapshots__/ManyOfAnt.test.tsx.snap
  packages/antd/src/__tests__/__snapshots__/NumericAnt.test.tsx.snap
  packages/antd/src/__tests__/__snapshots__/OneOfAnt.test.tsx.snap
  packages/antd/src/__tests__/__snapshots__/TableAnt.test.tsx.snap
  packages/antd/src/__tests__/__snapshots__/TextAnt.test.tsx.snap
  packages/antd/src/__tests__/__snapshots__/TimePickerAnt.test.tsx.snap
  packages/moxb/src/bind/Bind.ts
  packages/moxb/src/bind/BindImpl.ts
  packages/moxb/src/bind/__tests__/BindImpl.test.ts
Labels: PR - Under Review

#70 Add a widget for indicating process using antd steps
  packages/antd/src/routing/MultiStepProcessAnt.tsx
  packages/antd/src/routing/index.ts
  packages/moxb/src/routing/MultiStepProcess.ts
  packages/moxb/src/routing/index.ts
Labels: PR - Under Review

#71 Provide an easy way for defining/calling Meteor methods
  packages/meteor/src/MeteorMethod.ts
  packages/meteor/src/index.ts
Labels: PR - Under Review

#72 Support for creating Actions backed by Meteor methods
  packages/meteor/src/Bit.ts
  packages/meteor/src/MeteorAction.ts
  packages/meteor/src/index.ts
Labels: PR - Under Review

#73 Enhance the Link component
  examples/src/menus/MoreMenusAnt.tsx
  packages/antd/src/not-antd/Link.tsx
  packages/antd/src/not-antd/index.ts
  packages/antd/src/routing/LinkAnt.tsx
  packages/antd/src/routing/index.ts
Labels: PR - Ready for Review

#69 Markdown render support
  examples/src/app/Application.ts
  examples/src/app/ApplicationAnt.tsx
  examples/src/app/ApplicationImpl.ts
  package-lock.json
  packages/antd/package.json
  packages/antd/src/ConfirmAnt.tsx
  packages/antd/src/FormItemAnt.tsx
  packages/antd/src/LabelAnt.tsx
  packages/antd/src/__tests__/__snapshots__/ConfirmAnt.test.tsx.snap
  packages/antd/src/index.ts
  packages/html/src/ActionHtml.tsx
  packages/moxb/src/impl.ts
  packages/moxb/src/label/Label.ts
  packages/moxb/src/label/LabelImpl.ts
  packages/moxb/src/types.ts
  packages/semui/package.json
  packages/semui/src/LabelUi.tsx
  packages/semui/src/index.ts
Labels: PR - Under Review

#76 Added KeyboardShortcutManager
  packages/antd/src/__tests__/__snapshots__/ActionAnt.test.tsx.snap
  packages/moxb/src/action/Action.ts
  packages/moxb/src/action/ActionImpl.ts
  packages/moxb/src/action/__tests__/Action.test.ts
  packages/moxb/src/bind/BindImpl.ts
  packages/moxb/src/impl.ts
  packages/moxb/src/keyboard-shortcuts/KeyboardShortcutsManager.ts
  packages/moxb/src/keyboard-shortcuts/KeyboardShortcutsManagerImpl.ts
  packages/moxb/src/keyboard-shortcuts/__tests__/KeyboardShortcutsManager.test.ts
  packages/moxb/src/keyboard-shortcuts/__tests__/__snapshots__/KeyboardShortcutsManager.test.ts.snap
  packages/moxb/src/types.ts
Labels: PR - Under Review

#77 Add an Error class that work well for forms
  packages/meteor/src/MeteorMethod.ts
Labels: PR - Under Review

#74 Enhance Actions with Promise interface
  packages/antd/src/__tests__/__snapshots__/ActionAnt.test.tsx.snap
  packages/meteor/src/MeteorAction.ts
  packages/moxb/src/action/Action.ts
  packages/moxb/src/action/ActionImpl.ts
Labels: PR - Under Review

#78 Add unit support for numeric inputs
  examples/src/app/ApplicationImpl.ts
  packages/antd/src/NumericAnt.tsx
  packages/antd/src/__tests__/__snapshots__/NumericAnt.test.tsx.snap
  packages/moxb/src/numeric/Numeric.ts
  packages/moxb/src/numeric/NumericImpl.ts
Labels: PR - Under Review

#75 ActionSpanAnt
  examples/src/app/ApplicationAnt.tsx
  packages/antd/src/ActionAnt.tsx
  packages/antd/src/routing/LinkAnt.tsx
  packages/antd/src/routing/index.ts
Labels: PR - Under Review

#79 Support showing a title on menu items when the cursor hovers
  packages/antd/src/routing/NavMenuBarAnt.tsx
  packages/moxb/src/routing/location-state-space/state-space/StateSpace.ts
Labels: Enhancement, PR - Ready for Review

#80 Fix incorrect use of Ant radio groups
  packages/antd/src/OneOfAnt.tsx
  packages/antd/src/__tests__/__snapshots__/OneOfAnt.test.tsx.snap
Labels: Bug, PR - Under Review

#81 Comfirm bug fix
  packages/antd/src/__tests__/__snapshots__/ConfirmAnt.test.tsx.snap
  packages/moxb/src/confirm/ConfirmImpl.ts
  packages/moxb/src/confirm/__tests__/ConfirmImpl.test.ts
Labels: PR - Ready for Review
