Repository moxb/moxb, pull requests merged in 2018-11, with the labels that each got.

#49 Get rid of the unwanted React dependency of the moxb package
  examples/src/MenuStructure.tsx
  examples/src/menus/SubMenu.tsx
  package-lock.json
  packages/antd/src/not-antd/Anchor.tsx
  packages/antd/src/not-antd/LocationDependentArea.tsx
  packages/antd/src/not-antd/UIFragment.ts
  packages/antd/src/not-antd/UIFragmentSpec.ts
  packages/antd/src/not-antd/__tests__/UIFragmentSpec.test.ts
  packages/antd/src/not-antd/index.ts
  packages/antd/src/routing/NavMenuBarAnt.tsx
  packages/moxb/package.json
  packages/moxb/src/routing/index.ts
  packages/moxb/src/routing/location-state-space/LocationDependentStateSpaceHandler.ts
  packages/moxb/src/routing/location-state-space/LocationDependentStateSpaceHandlerImpl.ts
  packages/moxb/src/routing/location-state-space/state-space/StateSpace.ts
  packages/moxb/src/routing/location-state-space/state-space/StateSpaceHandler.ts
  packages/moxb/src/routing/location-state-space/state-space/StateSpaceHandlerImpl.ts
  packages/moxb/src/routing/location-state-space/state-space/SubStateKeyGenerator.ts
  packages/moxb/src/routing/location-state-space/state-space/SubStateKeyGeneratorImpl.ts
  packages/moxb/src/routing/location-state-space/state-space/__tests__/TestStateSpace.ts
Labels: @moxb, PR - Under Review

#48 Args parser does not use memorize
  package-lock.json
  packages/moxb/package.json
  packages/moxb/src/routing/url-arg/UrlArgTypes.ts
  packages/moxb/src/routing/url-arg/__tests__/UrlArgTypeOrderedStringArray.test.ts
  packages/moxb/src/routing/url-arg/__tests__/UrlArgTypeUnorderedStringArray.test.ts
Labels: @moxb, PR - Ready for Review

#50 Hotfix action children
  packages/antd/src/FormItemAnt.tsx
Labels: PR - Under Review

#53 Remove unwanted default value arg for url arg parsers
  packages/moxb/src/routing/location-state-space/LocationDependentStateSpaceHandlerImpl.ts
  packages/moxb/src/routing/url-arg/UrlArg.ts
  packages/moxb/src/routing/url-arg/UrlArgImpl.ts
  packages/moxb/src/routing/url-arg/UrlArgTypes.ts
  packages/moxb/src/routing/url-arg/__tests__/UrlArgImpl.test.ts
  packages/moxb/src/routing/url-arg/__tests__/UrlArgTypeBoolean.test.ts
  packages/moxb/src/routing/url-arg/__tests__/UrlArgTypeOrderedStringArray.test.ts
  packages/moxb/src/routing/url-arg/__tests__/UrlArgTypeUnorderedStringArray.test.ts
Labels: PR - Under Review

#57 Clean up mobx and mobx-react versions
  examples/package-lock.json
  examples/package.json
  package-lock.json
  packages/antd/package-lock.json
  packages/antd/package.json
  packages/meteor/package-lock.json
  packages/meteor/package.json
  packages/moxb/package.json
  packages/semui/package-lock.json
  packages/semui/package.json
Labels: PR - Under Review

#58 Replace wget with curl
  Makefile
  admin/node-installation/install.sh
Labels: PR - Under Review

#59 Improve the path token matching API
  examples/src/app/AppRouterAnt.tsx
  examples/src/menus/DetailDisplayer.tsx
  examples/src/menus/MoreMenusAnt.tsx
  examples/src/menus/SubMenu.tsx
  examples/src/store/Store.ts
  examples/src/store/UrlStore.ts
  examples/src/store/UrlStoreImpl.ts
  packages/antd/src/not-antd/LocationDependentArea.tsx
  packages/moxb/src/routing/TokenManager.ts
  packages/moxb/src/routing/TokenManagerImpl.ts
  packages/moxb/src/routing/location-state-space/LocationDependentStateSpaceHandler.ts
  packages/moxb/src/routing/location-state-space/LocationDependentStateSpaceHandlerImpl.ts
  packages/moxb/src/routing/location-state-space/state-space/StateSpaceHandler.ts
  packages/moxb/src/routing/location-state-space/state-space/StateSpaceHandlerImpl.ts
  packages/moxb/src/routing/url-arg/UrlTokenImpl.ts
Labels: PR - Under Review

#61 use observable stuct for datafetcher
  packages/antd/src/TableAnt.tsx
  packages/antd/src/__tests__/__snapshots__/TableAnt.test.tsx.snap
  packages/meteor/src/MethodDataFetcherImpl.ts
  packages/moxb/src/table/TableSort.ts
  packages/moxb/src/table/TableSortImpl.ts
Labels: @moxb/antd, @moxb/meteor, PR - Ready for Review

#62 Herndl/52 table width
  packages/antd/src/TableAnt.tsx
  packages/antd/src/__tests__/__snapshots__/TableAnt.test.tsx.snap
  packages/moxb/src/table/TableColumn.ts
  packages/moxb/src/table/TableColumnImpl.ts
Labels: PR - Under Review

#63 Support dynamic forms
  packages/moxb/src/form/FormImpl.ts
Labels: PR - Under Review
